package com.hotpads.datarouter.serialize.fieldcache;

import java.util.List;
import java.util.Map;

import org.apache.log4j.Logger;

import com.google.common.base.Preconditions;
import com.hotpads.datarouter.client.imp.hbase.node.HBaseReaderNode;
import com.hotpads.datarouter.client.imp.jdbc.ddl.domain.MySqlCharacterSet;
import com.hotpads.datarouter.client.imp.jdbc.ddl.domain.MySqlCollation;
import com.hotpads.datarouter.node.NodeParams;
import com.hotpads.datarouter.serialize.fielder.DatabeanFielder;
import com.hotpads.datarouter.serialize.fielder.PrimaryKeyFielder;
import com.hotpads.datarouter.storage.databean.Databean;
import com.hotpads.datarouter.storage.entity.Entity;
import com.hotpads.datarouter.storage.field.Field;
import com.hotpads.datarouter.storage.field.FieldSet;
import com.hotpads.datarouter.storage.field.FieldTool;
import com.hotpads.datarouter.storage.field.SimpleFieldSet;
import com.hotpads.datarouter.storage.field.imp.positive.UInt63Field;
import com.hotpads.datarouter.storage.key.entity.EntityKey;
import com.hotpads.datarouter.storage.key.entity.EntityPartitioner;
import com.hotpads.datarouter.storage.key.primary.EntityPrimaryKey;
import com.hotpads.datarouter.storage.key.primary.PrimaryKey;
import com.hotpads.datarouter.storage.prefix.EmptyScatteringPrefix;
import com.hotpads.datarouter.storage.prefix.ScatteringPrefix;
import com.hotpads.util.core.ByteTool;
import com.hotpads.util.core.ClassTool;
import com.hotpads.util.core.CollectionTool;
import com.hotpads.util.core.IterableTool;
import com.hotpads.util.core.ListTool;
import com.hotpads.util.core.MapTool;
import com.hotpads.util.core.StringTool;
import com.hotpads.util.core.bytes.StringByteTool;
import com.hotpads.util.core.java.ReflectionTool;

public class DatabeanFieldInfo<
		PK extends PrimaryKey<PK>,
		D extends Databean<PK,D>,
		F extends DatabeanFielder<PK,D>> {
	private static Logger logger = Logger.getLogger(DatabeanFieldInfo.class);
	
	public static final byte ENTITY_PREFIX_TERMINATOR = 0;
	
	//these 4 fields only apply to physical nodes, but cleanest to add them here for now
	private String clientName;
	private String tableName;
	private String packagedTableName;
	private String explicitNodeName;
	
	private Class<PK> primaryKeyClass;
	private PK samplePrimaryKey;
	private Class<? super D> baseDatabeanClass;
	private Class<D> databeanClass;
	private D sampleDatabean;
	private String keyFieldName;
	private java.lang.reflect.Field keyJavaField;
	private Map<String,List<Field<?>>>  indexes; // !new! the indexes in the databean
	private MySqlCollation collation; // !new! the collation of the table
	private MySqlCharacterSet character_set; // !new! the character set of the table
	
	private boolean entity = false;
	private Class<? extends Entity> entityClass;
	private String entityTableName;
	private String entityNodePrefix;
	private byte[] entityNodeColumnPrefixBytes;
	private EntityKey sampleEntityKey;
	private Class<? extends EntityKey> entityKeyClass;
	private Class<? extends EntityPartitioner<?>> entityPartitionerClass;
	private EntityPartitioner<?> entityPartitioner;
	private List<Field<?>> entityKeyFields;
	private List<Field<?>> postEkPkKeyFields;
	
	private Class<? extends ScatteringPrefix> scatteringPrefixClass;
	private ScatteringPrefix sampleScatteringPrefix;
	private List<Field<?>> scatteringPrefixFields;
	
	private Class<F> fielderClass;
	private F sampleFielder;
	private Class<PrimaryKeyFielder<PK>> primaryKeyFielderClass;
	private PrimaryKeyFielder<PK> samplePrimaryKeyFielder;

	private boolean fieldAware;
	private boolean autogeneratedId;
	private String autogeneratedFieldName;
	//these hold separate deep-copies of the fields
	private List<Field<?>> primaryKeyFields;//no prefixes
	private List<Field<?>> prefixedPrimaryKeyFields;//no prefixes
	private List<Field<?>> nonKeyFields;
	private List<Field<?>> fields;//PK fields will have prefixes in this Collection
	

	private Map<String,Field<?>> primaryKeyFieldByName = MapTool.createHashMap();
	private Map<String,Field<?>> nonKeyFieldByColumnName = MapTool.createHashMap();
	private Map<String,Field<?>> fieldByColumnName = MapTool.createHashMap();
	private Map<String,Field<?>> fieldByPrefixedName = MapTool.createHashMap();
	
	private List<String> fieldNames = ListTool.createArrayList();
	private List<java.lang.reflect.Field> reflectionFields = ListTool.createArrayList();
	private Map<String,java.lang.reflect.Field> reflectionFieldByName = MapTool.createHashMap();
	
	
//	public DatabeanFieldInfo(String nodeName, Class<D> databeanClass, Class<F> fielderClass){
	public DatabeanFieldInfo(String nodeName, NodeParams<PK,D,F> params){
		this.databeanClass = params.getDatabeanClass();
		this.sampleDatabean = ReflectionTool.create(databeanClass);
		this.primaryKeyClass = this.sampleDatabean.getKeyClass();
		this.samplePrimaryKey = ReflectionTool.create(primaryKeyClass);
		this.keyFieldName = sampleDatabean.getKeyFieldName();
		this.fielderClass = params.getFielderClass();
		this.fieldAware = fielderClass != null;
		this.autogeneratedId = detectAutogeneratedId();
		
		try{
			/*
			 * TODO remove duplicate logic below, but watch out for handling of non fieldAware databeans
			 */
			this.primaryKeyFields = samplePrimaryKey.getFields();
			this.prefixedPrimaryKeyFields = sampleDatabean.getKeyFields();
			addPrimaryKeyFieldsToCollections();
			if(fielderClass==null){
				Preconditions.checkArgument(!fieldAware, nodeName+" is field aware but has no Fielder");
				if(fieldAware){
					throw new IllegalArgumentException("could not instantiate "+nodeName
							+", fieldAware databean node must specify fielder class");
				}
				this.scatteringPrefixClass = EmptyScatteringPrefix.class;
			}else{
				this.sampleFielder = ReflectionTool.create(fielderClass);
				//TODO remove the cast after fixing the DatabeanFielder interface and changing all databeans
				this.primaryKeyFielderClass = (Class<PrimaryKeyFielder<PK>>)sampleFielder.getKeyFielderClass();
				this.samplePrimaryKeyFielder = ReflectionTool.create(primaryKeyFielderClass);
				this.primaryKeyFields = samplePrimaryKeyFielder.getFields(sampleDatabean.getKey());
				this.prefixedPrimaryKeyFields = sampleFielder.getKeyFields(sampleDatabean);

				Preconditions.checkArgument(fieldAware, nodeName+" specified a Fielder but is not FieldAware");
//				if(fieldAware){
					this.fields = sampleFielder.getFields(sampleDatabean);//make sure there is a PK or this will NPE
					addFieldsToCollections();
					this.nonKeyFields = sampleFielder.getNonKeyFields(sampleDatabean);//only do these if the previous fields succeeded	
					addNonKeyFieldsToCollections();
					this.indexes = sampleFielder.getIndexes(sampleDatabean);
					this.character_set = sampleFielder.getCharacterSet(sampleDatabean);
					this.collation = sampleFielder.getCollation(sampleDatabean);
//				}
				this.scatteringPrefixClass = sampleFielder.getScatteringPrefixClass();
				assertNoScatteringPrefixOnDeprecatedTables();
			}
			if(fieldAware){
//				FieldTool.cacheReflectionInfo(scatteringPrefixFields, sampleScatterPrefix);
				FieldTool.cacheReflectionInfo(primaryKeyFields, samplePrimaryKey);
				FieldTool.cacheReflectionInfo(nonKeyFields, sampleDatabean);
				FieldTool.cacheReflectionInfo(fields, sampleDatabean);
			}
			this.sampleScatteringPrefix = ReflectionTool.create(scatteringPrefixClass);
			this.scatteringPrefixFields = sampleScatteringPrefix.getScatteringPrefixFields(samplePrimaryKey);
		}catch(Exception probablyNoPkInstantiated){
			throw new IllegalArgumentException("could not instantiate "+nodeName, probablyNoPkInstantiated);
		}
		
		//entity stuff
		this.entityTableName = params.getEntityTableName();
		this.entity = StringTool.notEmpty(entityTableName);
		if(entity){
			//key java field is currently only used for entity keys.  won'y work for databans with a dynamically created PK
			this.keyJavaField = ReflectionTool.getDeclaredFieldFromHierarchy(databeanClass, keyFieldName);
			this.entityClass = Preconditions.checkNotNull(params.getEntityClass());
			if(StringTool.isEmpty(params.getEntityNodePrefix())){
				throw new IllegalArgumentException("must specify entityNodePrefix for entity nodes");
			}
			this.entityNodePrefix = params.getEntityNodePrefix();
			this.entityNodeColumnPrefixBytes = ByteTool.concatenate(StringByteTool.getUtf8Bytes(entityNodePrefix), 
					new byte[]{ENTITY_PREFIX_TERMINATOR});
			EntityPrimaryKey<?,?> sampleEntityPrimaryKey = (EntityPrimaryKey<?,?>)samplePrimaryKey;
			this.sampleEntityKey = sampleEntityPrimaryKey.getEntityKey();
			this.entityKeyClass = sampleEntityKey.getClass();
			this.entityPartitionerClass = params.getEntityPartitionerClass();
			this.entityPartitioner = ReflectionTool.create(entityPartitionerClass);
			//careful to call sampleEntityPrimarykey.getEntityKeyFields vs sampleEntityKey.getFields().  the pk may override the ek
			this.entityKeyFields = sampleEntityPrimaryKey.getEntityKeyFields();
			this.postEkPkKeyFields = sampleEntityPrimaryKey.getPostEntityKeyFields();
		}
		
		//info about PhysicalNodes, the leaf nodes that store the data (as opposed to virtual nodes)
		this.clientName = params.getClientName();
		this.baseDatabeanClass = databeanClass;
		if(StringTool.notEmpty(params.getPhysicalName())){//explicitly set tableName
			this.tableName = params.getPhysicalName();
			this.packagedTableName = params.getQualifiedPhysicalName();
			explicitNodeName = clientName+"."+tableName;
			logger.info("client:"+clientName+" "+params.getDatabeanClass().getSimpleName()+" overridden -> "+tableName);
		}else if(entity){
			this.tableName = entityTableName;
			this.packagedTableName = null;//what to do here
		}else if(params.getBaseDatabeanClass() != null){//table-per-class-hierarchy (use superclass's table)
			this.tableName = params.getBaseDatabeanClass().getSimpleName();
			this.packagedTableName = params.getDatabeanClass().getName();
			this.baseDatabeanClass = params.getBaseDatabeanClass();
			logger.info("client:"+clientName+" "+params.getDatabeanClass().getSimpleName()+" in superclass -> "+tableName);
		}else{//default to using the databean's name as the table name
			this.tableName = params.getDatabeanClass().getSimpleName();
			this.packagedTableName = params.getDatabeanClass().getName();
		}
		
		assertAssertions();
	}
	
	
	/***************************** methods **************************************************/
	
	//loose safety check
	private void assertNoScatteringPrefixOnDeprecatedTables(){
		String tableName = databeanClass.getSimpleName();
		if(ClassTool.differentClass(scatteringPrefixClass, EmptyScatteringPrefix.class) 
				&& HBaseReaderNode.TRAILING_BYTE_TABLES.contains(tableName)){
			throw new IllegalArgumentException("don't add scattering prefix to broken table!:"+tableName);
		}
	}
	
	public FieldSet<?> getScatteringPrefixPlusPrimaryKey(PK key){
		return new SimpleFieldSet(getKeyFieldsWithScatteringPrefix(key));
	}
	
	public List<Field<?>> getKeyFieldsWithScatteringPrefix(PK key){
		List<Field<?>> fields = ListTool.createLinkedList();
		fields.addAll(sampleScatteringPrefix.getScatteringPrefixFields(key));
		if(key==null){ return fields; }
		fields.addAll(key.getFields());
		return fields;
	}
	
	public Class<? extends Field> getFieldTypeForColumn(String columnName){
		Field<?> field = fieldByColumnName.get(columnName);
		return field.getClass();//throw NPE for invalid column name
	}
	
//	public List<Field<?>> getStartOfNextScatteringPrefix(PK key){
//		List<Field<?>> fields = ListTool.createLinkedList();
//		fields.addAll(sampleScatteringPrefix.getScatteringPrefixFields(key));
//		if(key==null){ return fields; }
//		fields.addAll(key.getFields());
//		return fields;
//	}
	
	public List<Field<?>> getPrimaryKeyFieldsWithValues(D d){
		return sampleFielder.getKeyFields(d);
	}
	
	public List<Field<?>> getFieldsWithValues(D d){
		return sampleFielder.getFields(d);
	}
	
	public List<Field<?>> getNonKeyFieldsWithValues(D d){
//		if(d==null){ return ListTool.createLinkedList(); }
//		if(fielderClass==null){ return d.getFields(); }
		return sampleFielder.getNonKeyFields(d);
	}
	
	private void addPrimaryKeyFieldsToCollections(){
		for(Field<?> field : IterableTool.nullSafe(primaryKeyFields)){
			this.primaryKeyFieldByName.put(field.getName(), field);
		}
	}
	
	private void addNonKeyFieldsToCollections(){
		for(Field<?> field : IterableTool.nullSafe(nonKeyFields)){
			this.nonKeyFieldByColumnName.put(field.getColumnName(), field);
		}
	}
	
	private void addFieldsToCollections(){
		for(Field<?> field : IterableTool.nullSafe(fields)){
			this.fieldByColumnName.put(field.getColumnName(), field);
			this.fieldByPrefixedName.put(field.getPrefixedName(), field);
			this.fieldNames.add(field.getName());
			java.lang.reflect.Field reflectionField = FieldTool.getReflectionFieldForField(sampleDatabean, field);
			this.reflectionFields.add(reflectionField);
			this.reflectionFieldByName.put(field.getName(), reflectionField);
		}
	}
	
	private void assertAssertions(){
		if(fieldAware){
			if(CollectionTool.notEmpty(nonKeyFields)){
				if(!fieldAware){
					logger.warn("found nonKeyFields on non-fieldAware databean "+databeanClass.getName());
				}
			}
			for(Field<?> field : primaryKeyFields){
//				if(StringTool.notEmpty(field.getPrefix())){
//					logger.warn("found unusual prefix on primaryKeyField "+primaryKeyClass.getName());
//				}
			}
		}
	}
	
	private boolean detectAutogeneratedId(){
		List<Field<?>> fields = samplePrimaryKey.getFields();
		for (Field<?> f : fields) {
			if (f instanceof UInt63Field) {
				UInt63Field uInt63Field = (UInt63Field) f;
				if (uInt63Field.isAutoGenerated()) {
					setAutogeneratedFieldName(uInt63Field.getName());
					return true;
				}
			}
		}
		
		return false;
	}

	
	/******************************** get/set **********************************************/

	public Class<PK> getPrimaryKeyClass(){
		return primaryKeyClass;
	}

	public PK getSamplePrimaryKey(){
		return samplePrimaryKey;
	}

	public Class<? super D> getBaseDatabeanClass(){
		return baseDatabeanClass;
	}

	public void setBaseDatabeanClass(Class<? super D> baseDatabeanClass){
		this.baseDatabeanClass = baseDatabeanClass;
	}

	public Class<D> getDatabeanClass(){
		return databeanClass;
	}

	public D getSampleDatabean(){
		return sampleDatabean;
	}

	public Class<F> getFielderClass(){
		return fielderClass;
	}

	public F getSampleFielder(){
		return sampleFielder;
	}

	public boolean getFieldAware(){
		return fieldAware;
	}

	public List<Field<?>> getPrimaryKeyFields(){
		return primaryKeyFields;
	}

	public List<Field<?>> getNonKeyFields(){
		return nonKeyFields;
	}

	public List<Field<?>> getFields(){
		return fields;
	}

	public Map<String,Field<?>> getNonKeyFieldByColumnName(){
		return nonKeyFieldByColumnName;
	}

	public Map<String,Field<?>> getFieldByColumnName(){
		return fieldByColumnName;
	}

	public List<String> getFieldNames(){
		return fieldNames;
	}

	public List<java.lang.reflect.Field> getReflectionFields(){
		return reflectionFields;
	}

	public Map<String,java.lang.reflect.Field> getReflectionFieldByName(){
		return reflectionFieldByName;
	}

	public Map<String,Field<?>> getFieldByPrefixedName(){
		return fieldByPrefixedName;
	}

	public String getKeyFieldName(){
		return keyFieldName;
	}

	public List<Field<?>> getPrefixedPrimaryKeyFields(){
		return prefixedPrimaryKeyFields;
	}

	public Class<? extends ScatteringPrefix> getScatteringPrefixClass(){
		return scatteringPrefixClass;
	}

	public List<Field<?>> getScatteringPrefixFields(){
		return scatteringPrefixFields;
	}

	public ScatteringPrefix getSampleScatteringPrefix(){
		return sampleScatteringPrefix;
	}

	public Map<String,List<Field<?>>> getIndexes(){
		return indexes;
	}
	
	public MySqlCollation getCollation(){
		return collation;
	}
	
	public MySqlCharacterSet getCharacterSet(){
		return character_set;
	}

	public Map<String,Field<?>> getPrimaryKeyFieldByName(){
		return primaryKeyFieldByName;
	}

	public boolean isAutogeneratedId(){
		return autogeneratedId;
	}

	public String getAutogeneratedFieldName(){
		return autogeneratedFieldName;
	}

	public void setAutogeneratedFieldName(String autogeneratedFieldName){
		this.autogeneratedFieldName = autogeneratedFieldName;
	}
	
	public void setFields(List<Field<?>> fields){
		this.fields = fields;
	}

	public MySqlCharacterSet getCharacter_set(){
		return character_set;
	}

	public Class<PrimaryKeyFielder<PK>> getPrimaryKeyFielderClass(){
		return primaryKeyFielderClass;
	}

	public PrimaryKeyFielder<PK> getSamplePrimaryKeyFielder(){
		return samplePrimaryKeyFielder;
	}

	public String getTableName(){
		return tableName;
	}

	public String getExplicitNodeName(){
		return explicitNodeName;
	}

	public String getPackagedTableName(){
		return packagedTableName;
	}

	public String getClientName(){
		return clientName;
	}

	public String getEntityName(){
		return entityTableName;
	}

	public String getEntityNodePrefix(){
		return entityNodePrefix;
	}

	public byte[] getEntityColumnPrefixBytes(){
		return entityNodeColumnPrefixBytes;
	}

	public java.lang.reflect.Field getKeyJavaField(){
		return keyJavaField;
	}

	public boolean isEntity(){
		return entity;
	}
	
	public Class<? extends Entity> getEntityClass(){
		return entityClass;
	}
	
	public EntityPartitioner<?> getEntityPartitioner(){
		return entityPartitioner;
	}

	public Class<? extends EntityKey> getEntityKeyClass(){
		return entityKeyClass;
	}

	public EntityKey getSampleEntityKey(){
		return sampleEntityKey;
	}

	public List<Field<?>> getEntityKeyFields(){
		return entityKeyFields;
	}

	public List<Field<?>> getPostEkPkKeyFields(){
		return postEkPkKeyFields;
	}
}
