package com.hotpads.datarouter.client.imp.jdbc.ddl;

public enum MysqlColumnType {

	/*
	 * NOT TAKING INTO ACCOUNT OPTIONS AVAILABLE FOR THE DIFFERENT TYPES
	 */
	 //  Numeric Type Overview 
	BIT, TINYINT, BOOL, BOOLEAN, SMALLINT, MEDIUMINT, INT, INTEGER, BIGINT, DECIMAL, DEC /* SIMILAR TO DECIMAL, HAS 'FIXED' FOR COMPATIBILITY */, FLOAT, DOUBLE, DOUBLE_PRECISION, /* FLOAT(P) */
	
	// Date and Time Type Overview
	DATE, DATETIME, TIMESTAMP, TIME, YEAR,
	
	// String Type Overview
	CHAR, VARCHAR, BINARY, VARBINARY, TINYBLOB, TINYTEXT, BLOB, TEXT, MEDIUMBLOB, MEDIUMTEXT, LONGBLOB, LONGTEXT, ENUM, SET;

}
