package com.hotpads.datarouter.storage.field;

import com.hotpads.datarouter.storage.field.encoding.FieldGeneratorType;


/**
 * FieldKey is a mapping from a java field to the datastore. When using an RDBMS, FieldKey defines the column name,
 * datatype, and metadata.
 * 
 * The getName() method refers to the java field's name. This name is used to choose the default datastore column name,
 * but the datastore column name can be overridden with getColumnName().
 * 
 * FieldKeys are immutable so may be defined as constants and reused across many Field objects.
 */
public interface FieldKey<T>{

	String getName();
	
	String getColumnName();
	byte[] getColumnNameBytes();
	
	boolean isNullable();
	
	FieldGeneratorType getAutoGeneratedType();
	
	boolean isFixedLength();
	
	boolean isCollection();//this is used by viewNodeData.jsp to add line breaks to the table
	T getDefaultValue();
	
}