package com.hotpads.datarouter.storage.field.encoding;

import com.hotpads.datarouter.storage.field.Field;


public interface AutoGeneratedField<T> extends Field<T>{

	public AutoGeneratedType getAutoGeneratedType();
	public Field<T> setAutoGenerated(AutoGeneratedType type);
	
	public static enum AutoGeneratedType{
		MANAGED, RANDOM;
	}
	
}
