/**
 * Copyright © 2009 HotPads (admin@hotpads.com)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.datarouter.storage.serialize.fieldcache;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.function.Supplier;

import io.datarouter.model.databean.Databean;
import io.datarouter.model.field.Field;
import io.datarouter.model.field.encoding.FieldGeneratorType;
import io.datarouter.model.key.primary.EntityPrimaryKey;
import io.datarouter.model.key.primary.PrimaryKey;
import io.datarouter.model.serialize.fielder.DatabeanFielder;
import io.datarouter.storage.node.NodeParams;
import io.datarouter.storage.setting.Setting;
import io.datarouter.util.bytes.ByteTool;
import io.datarouter.util.bytes.StringByteTool;
import io.datarouter.util.iterable.IterableTool;
import io.datarouter.util.lang.ReflectionTool;
import io.datarouter.util.string.StringTool;

public class DatabeanFieldInfo<
		PK extends PrimaryKey<PK>,
		D extends Databean<PK,D>,
		F extends DatabeanFielder<PK,D>>{

	private static final byte ENTITY_PREFIX_TERMINATOR = 0;

	private final Class<PK> primaryKeyClass;
	private final PK samplePrimaryKey;
	private final Supplier<D> databeanSupplier;
	private final D sampleDatabean;
	private java.lang.reflect.Field keyJavaField;
	private final Map<String,List<Field<?>>> uniqueIndexes;

	private boolean entity = false;
	private String entityNodePrefix;
	private byte[] entityNodeColumnPrefixBytes;
	private List<Field<?>> ekFields;//for accessing the EK directly
	private List<Field<?>> ekPkFields;//for accessing the EK via a PK
	private List<Field<?>> postEkPkKeyFields;

	private final Supplier<F> fielderSupplier;
	private final F sampleFielder;

	private final FieldGeneratorType autoGeneratedType;
	private String autoGeneratedFieldName;
	private final Optional<Long> ttlMs;
	//these hold separate deep-copies of the fields
	private final List<Field<?>> primaryKeyFields;//no prefixes
	private final List<Field<?>> nonKeyFields;
	private final List<Field<?>> fields;//PK fields will have prefixes in this Collection

	private final Setting<Boolean> recordCallsite;

	private final Map<String,Field<?>> nonKeyFieldByColumnName = new HashMap<>();
	private final Map<String,Field<?>> fieldByColumnName = new HashMap<>();
	private final Map<String,Field<?>> fieldByPrefixedName = new HashMap<>();

	public DatabeanFieldInfo(NodeParams<PK,D,F> params){
		this.databeanSupplier = params.getDatabeanSupplier();
		this.sampleDatabean = databeanSupplier.get();
		this.primaryKeyClass = this.sampleDatabean.getKeyClass();
		this.samplePrimaryKey = ReflectionTool.create(primaryKeyClass);
		this.fielderSupplier = params.getFielderSupplier();
		this.sampleFielder = fielderSupplier.get();
		this.autoGeneratedType = detectAutoGeneratedType();
		this.ttlMs = sampleFielder.getTtlMs();

		this.recordCallsite = params.getRecordCallsites();

		try{
			this.primaryKeyFields = samplePrimaryKey.getFields();

			this.fields = sampleFielder.getFields(sampleDatabean);//make sure there is a PK or this will NPE
			addFieldsToCollections();
			//only do these if the previous fields succeeded
			this.nonKeyFields = sampleFielder.getNonKeyFields(sampleDatabean);
			addNonKeyFieldsToCollections();
			this.uniqueIndexes = new HashMap<>(sampleFielder.getUniqueIndexes(sampleDatabean));
		}catch(Exception probablyNoPkInstantiated){
			throw new IllegalArgumentException("could not instantiate node params", probablyNoPkInstantiated);
		}

		//entity stuff
		this.entity = StringTool.notEmpty(params.getEntityNodePrefix());
		if(entity){
			//key java field is currently only used for entity keys.  won't work for databeans with a dynamically
			// created PK
			this.keyJavaField = ReflectionTool.getDeclaredFieldFromAncestors(sampleDatabean.getClass(),
					sampleDatabean.getKeyFieldName());
			if(StringTool.isEmpty(params.getEntityNodePrefix())){
				throw new IllegalArgumentException("must specify entityNodePrefix for entity nodes");
			}
			this.entityNodePrefix = params.getEntityNodePrefix();
			this.entityNodeColumnPrefixBytes = ByteTool.concatenate(StringByteTool.getUtf8Bytes(entityNodePrefix),
					new byte[]{ENTITY_PREFIX_TERMINATOR});
			EntityPrimaryKey<?,?> sampleEntityPrimaryKey = (EntityPrimaryKey<?,?>)samplePrimaryKey;
			this.ekFields = sampleEntityPrimaryKey.getEntityKey().getFields();
			this.ekPkFields = sampleEntityPrimaryKey.getEntityKeyFields();
			this.postEkPkKeyFields = sampleEntityPrimaryKey.getPostEntityKeyFields();
		}
	}

	/*----------------------------- methods ---------------------------------*/

	public Field<?> getFieldForColumnName(String columnName){
		return fieldByColumnName.get(columnName);
	}

	public List<Field<?>> getFieldsWithValues(D databean){
		return sampleFielder.getFields(databean);
	}

	public List<Field<?>> getNonKeyFieldsWithValues(D databean){
		return sampleFielder.getNonKeyFields(databean);
	}

	private void addNonKeyFieldsToCollections(){
		for(Field<?> field : IterableTool.nullSafe(nonKeyFields)){
			this.nonKeyFieldByColumnName.put(field.getKey().getColumnName(), field);
		}
	}

	private void addFieldsToCollections(){
		for(Field<?> field : fields){
			this.fieldByColumnName.put(field.getKey().getColumnName(), field);
			this.fieldByPrefixedName.put(field.getPrefixedName(), field);
		}
	}

	private FieldGeneratorType detectAutoGeneratedType(){
		List<Field<?>> fields = samplePrimaryKey.getFields();
		for(Field<?> field : fields){
			if(field.getKey().getAutoGeneratedType().isGenerated()){
				this.autoGeneratedFieldName = field.getKey().getName();
				return field.getKey().getAutoGeneratedType();
			}
		}
		return FieldGeneratorType.NONE;
	}


	/*----------------------------- get/set ---------------------------------*/

	public Class<PK> getPrimaryKeyClass(){
		return primaryKeyClass;
	}

	public PK getSamplePrimaryKey(){
		return samplePrimaryKey;
	}

	public Supplier<D> getDatabeanSupplier(){
		return databeanSupplier;
	}

	public D getSampleDatabean(){
		return sampleDatabean;
	}

	public Supplier<F> getFielderSupplier(){
		return fielderSupplier;
	}

	public F getSampleFielder(){
		return sampleFielder;
	}

	public List<Field<?>> getPrimaryKeyFields(){
		return primaryKeyFields;
	}

	public List<Field<?>> getNonKeyFields(){
		return nonKeyFields;
	}

	public List<Field<?>> getFields(){
		return fields;
	}

	public Map<String,Field<?>> getNonKeyFieldByColumnName(){
		return nonKeyFieldByColumnName;
	}

	public Map<String,Field<?>> getFieldByPrefixedName(){
		return fieldByPrefixedName;
	}

	public Map<String,List<Field<?>>> getUniqueIndexes(){
		return uniqueIndexes;
	}

	public FieldGeneratorType getAutoGeneratedType(){
		return autoGeneratedType;
	}

	public boolean isManagedAutoGeneratedId(){
		return FieldGeneratorType.MANAGED.equals(autoGeneratedType);
	}

	public String getAutogeneratedFieldName(){
		return autoGeneratedFieldName;
	}

	public String getEntityNodePrefix(){
		return entityNodePrefix;
	}

	public byte[] getEntityColumnPrefixBytes(){
		return entityNodeColumnPrefixBytes;
	}

	public java.lang.reflect.Field getKeyJavaField(){
		return keyJavaField;
	}

	public boolean isEntity(){
		return entity;
	}

	public List<Field<?>> getEkFields(){
		return ekFields;
	}

	public List<Field<?>> getEkPkFields(){
		return ekPkFields;
	}

	public List<Field<?>> getPostEkPkKeyFields(){
		return postEkPkKeyFields;
	}

	public Optional<Long> getTtlMs(){
		return ttlMs;
	}

	public Setting<Boolean> getRecordCallsite(){
		return recordCallsite;
	}
}
