package com.hotpads.datarouter.test.node.basic.manyfield.test;

import java.io.IOException;
import java.util.Collection;
import java.util.List;

import org.apache.log4j.Logger;
import org.junit.Assert;
import org.junit.BeforeClass;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.junit.runners.Parameterized;
import org.junit.runners.Parameterized.Parameters;

import com.hotpads.datarouter.client.ClientType;
import com.hotpads.datarouter.test.DRTestConstants;
import com.hotpads.datarouter.test.node.basic.BasicNodeTestRouter;
import com.hotpads.datarouter.test.node.basic.BasicNodeTestRouter.SortedBasicNodeTestRouter;
import com.hotpads.datarouter.test.node.basic.manyfield.AutoGeneratedKeyBean;
import com.hotpads.datarouter.test.node.basic.manyfield.AutoGeneratedKeyBeanKey;
import com.hotpads.util.core.CollectionTool;
import com.hotpads.util.core.ListTool;

@RunWith(Parameterized.class)
public class AutoGeneratedKeyIntegrationTests {
	static Logger logger = Logger.getLogger(AutoGeneratedKeyIntegrationTests.class);
	
	/****************************** static ***********************************/

	@Parameters
	public static Collection<Object[]> parameters(){
		return ListTool.wrap(new Object[]{ClientType.hibernate});
//		return DRTestConstants.CLIENT_TYPE_OBJECT_ARRAYS;
	}
	
	@BeforeClass
	public static void init() throws IOException{	

	}
	
	/***************************** fields **************************************/
	
	protected ClientType clientType;
	protected BasicNodeTestRouter router;
	protected List<AutoGeneratedKeyBeanKey> keys;

	/***************************** constructors **************************************/

	public AutoGeneratedKeyIntegrationTests(ClientType clientType){
		this.clientType = clientType;
		this.router = new SortedBasicNodeTestRouter(DRTestConstants.CLIENT_drTestHibernate0,
				AutoGeneratedKeyIntegrationTests.class);
		this.keys = ListTool.create();
		if(ClientType.memcached!=clientType){
			router.autoGeneratedKeyBean().deleteAll(null);
			Assert.assertEquals(0, CollectionTool.size(router.autoGeneratedKeyBean().getAll(null)));
		}
	}

	/***************************** tests **************************************/

	@Test
	public void testNullKey(){
		if (!isHibernate()){
			return;
		}
		AutoGeneratedKeyBean bean = new AutoGeneratedKeyBean();
		System.out.println("key : " + bean.getKey().getId());
		Assert.assertNull(bean.getKey().getId());
		router.autoGeneratedKeyBean().put(bean, null);
		System.out.println("key after : " + bean.getKey().getId());
		Assert.assertNotNull(bean.getKey().getId());
		recordKey(bean.getKey());
//		Assert.assertNotNull(bean.getKey().getId());
	}
	
	@Test
	public void testBoolean(){
		if (!isHibernate()){
			return;
		}
		AutoGeneratedKeyBean bean = new AutoGeneratedKeyBean();
		
		//test true value
		bean.setBooleanField(true);
		router.autoGeneratedKeyBean().put(bean, null);
		AutoGeneratedKeyBean roundTripped = router.autoGeneratedKeyBean().get(bean.getKey(), null);
		Assert.assertNotSame(bean, roundTripped);
		Assert.assertEquals(bean.getBooleanField(), roundTripped.getBooleanField());

		//test false value
		bean.setBooleanField(false);
		router.autoGeneratedKeyBean().put(bean, null);
		AutoGeneratedKeyBean roundTrippedFalse = router.autoGeneratedKeyBean().get(bean.getKey(), null);
		Assert.assertNotSame(bean, roundTripped);
		Assert.assertEquals(bean.getBooleanField(), roundTrippedFalse.getBooleanField());
		
		recordKey(bean.getKey());
	}
	
	
	/************************** tests for unmarshalling into databeans (a little out of place here **************/
	
	@Test 
	public void testGetAll(){
		if(!isHibernate()){
			return;
		}
		List<AutoGeneratedKeyBean> allBeans = router.autoGeneratedKeyBean().getAll(null);
		Assert.assertTrue(CollectionTool.sameSize(keys, allBeans));
		
	}
	
	@Test
	public void testGetMulti(){
		if(!isHibernate()) {
			return;
		}
		List<AutoGeneratedKeyBean> allBeans = router.autoGeneratedKeyBean().getMulti(keys, null);
		Assert.assertTrue(CollectionTool.sameSize(keys, allBeans));
	}
	
	
	/************************* helpers ********************************************/
	
	protected void recordKey(AutoGeneratedKeyBeanKey key){
		keys.add(key);
	}
	
	public boolean isMemory(){
		return ClientType.memory == clientType;
	}

	public boolean isHibernate(){
		return ClientType.hibernate == clientType;
	}

	public boolean isHBase(){
		return ClientType.hbase == clientType;
	}

	public boolean isMemcached(){
		return ClientType.memcached == clientType;
	}
}
